# Generated by Django 4.1.5 on 2023-01-06 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('image', models.CharField(default='default', max_length=100)),
                ('descriptions', models.CharField(default='default', max_length=100)),
                ('amound', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 6, 18, 0, 28, 119449, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Creation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
