# Generated by Django 4.1.5 on 2023-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_creation_created_at_alter_creation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='image',
            field=models.ImageField(upload_to='creations'),
        ),
    ]
